import { TASTY_VERSION } from '../version';

import { getPrecompileStore, warnPrecompileOnce } from './runtime';
import type {
  TastyPrecompiledChunk,
  TastyPrecompiledDependencies,
  TastyPrecompiledManifest,
} from './types';

function isManifestShapeValid(manifest: TastyPrecompiledManifest): boolean {
  const dependencies = manifest?.dependencies;
  return (
    manifest.schemaVersion === 1 &&
    typeof manifest.id === 'string' &&
    manifest.id.length > 0 &&
    typeof manifest.tastyVersion === 'string' &&
    typeof manifest.namePrefix === 'string' &&
    typeof manifest.cssHash === 'string' &&
    manifest.cssHash.length > 0 &&
    Array.isArray(manifest.chunks) &&
    manifest.chunks.every(
      (chunk) =>
        typeof chunk.lookupKey === 'string' &&
        typeof chunk.className === 'string' &&
        Array.isArray(chunk.animations) &&
        chunk.animations.every((name: unknown) => typeof name === 'string'),
    ) &&
    !!dependencies &&
    Array.isArray(dependencies.properties) &&
    Array.isArray(dependencies.keyframes) &&
    Array.isArray(dependencies.fontFaces) &&
    Array.isArray(dependencies.counterStyles) &&
    Array.isArray(dependencies.functions) &&
    Array.isArray(dependencies.rscKeys)
  );
}

function sameStrings(a: readonly string[], b: readonly string[]): boolean {
  return a.length === b.length && a.every((value, index) => value === b[index]);
}

function mergeDependencies(
  current: TastyPrecompiledDependencies | undefined,
  next: TastyPrecompiledDependencies,
): TastyPrecompiledDependencies {
  const properties = new Map(
    current?.properties.map((item) => [item.name, item.definition]),
  );
  const keyframes = new Map<
    string,
    { name: string; contentKey: string; rscKeys: Set<string> }
  >();
  const counterStyles = new Map<string, Set<string>>();

  for (const item of current?.keyframes ?? []) {
    keyframes.set(item.contentKey, {
      ...item,
      rscKeys: new Set(item.rscKeys),
    });
  }
  for (const item of current?.counterStyles ?? []) {
    counterStyles.set(item.name, new Set(item.rscKeys));
  }

  for (const item of next.properties) {
    if (!properties.has(item.name)) properties.set(item.name, item.definition);
  }
  for (const item of next.keyframes) {
    let entry = keyframes.get(item.contentKey);
    if (!entry) {
      entry = { ...item, rscKeys: new Set() };
      keyframes.set(item.contentKey, entry);
    }
    for (const key of item.rscKeys) entry.rscKeys.add(key);
  }
  for (const item of next.counterStyles) {
    let keys = counterStyles.get(item.name);
    if (!keys) {
      keys = new Set();
      counterStyles.set(item.name, keys);
    }
    for (const key of item.rscKeys) keys.add(key);
  }

  return {
    properties: [...properties].map(([name, definition]) => ({
      name,
      definition,
    })),
    keyframes: [...keyframes.values()].map((item) => ({
      ...item,
      rscKeys: [...item.rscKeys],
    })),
    fontFaces: [...new Set([...(current?.fontFaces ?? []), ...next.fontFaces])],
    counterStyles: [...counterStyles].map(([name, rscKeys]) => ({
      name,
      rscKeys: [...rscKeys],
    })),
    functions: [...new Set([...(current?.functions ?? []), ...next.functions])],
    rscKeys: [...new Set([...(current?.rscKeys ?? []), ...next.rscKeys])],
  };
}

/** Register one immutable stylesheet manifest. Returns whether it is usable. */
export function registerPrecompiledManifest(
  manifest: TastyPrecompiledManifest,
): boolean {
  if (!isManifestShapeValid(manifest)) {
    warnPrecompileOnce(
      `invalid:${manifest?.id ?? 'unknown'}`,
      '[Tasty] Ignoring an invalid precompiled style manifest.',
    );
    return false;
  }

  if (manifest.tastyVersion !== TASTY_VERSION) {
    warnPrecompileOnce(
      `version:${manifest.id}:${manifest.tastyVersion}`,
      `[Tasty] Ignoring precompiled styles "${manifest.id}": generated by Tasty ${manifest.tastyVersion}, but the runtime is ${TASTY_VERSION}.`,
    );
    return false;
  }

  const store = getPrecompileStore();
  const existingManifest = store.manifests?.get(manifest.id);
  if (existingManifest) {
    if (existingManifest.cssHash === manifest.cssHash) return true;
    warnPrecompileOnce(
      `manifest-conflict:${manifest.id}`,
      `[Tasty] Ignoring conflicting precompiled styles "${manifest.id}": the id is already registered with a different CSS hash.`,
    );
    return false;
  }

  const manifestChunks = new Map<string, TastyPrecompiledChunk>();
  for (const chunk of manifest.chunks) {
    const duplicate = manifestChunks.get(chunk.lookupKey);
    if (
      duplicate &&
      (duplicate.className !== chunk.className ||
        !sameStrings(duplicate.animations, chunk.animations))
    ) {
      warnPrecompileOnce(
        `internal-chunk-conflict:${manifest.id}:${chunk.lookupKey}`,
        `[Tasty] Ignoring precompiled styles "${manifest.id}": the manifest maps one chunk lookup key more than once with different metadata.`,
      );
      return false;
    }
    manifestChunks.set(chunk.lookupKey, chunk);

    const existing = store.chunks?.get(chunk.lookupKey);
    if (
      existing &&
      (existing.className !== chunk.className ||
        !sameStrings(existing.animations, chunk.animations))
    ) {
      warnPrecompileOnce(
        `chunk-conflict:${chunk.lookupKey}`,
        `[Tasty] Ignoring precompiled styles "${manifest.id}": a chunk lookup key is already mapped to different metadata by "${existing.manifestId}".`,
      );
      return false;
    }
  }

  if (store.manifests) {
    const propertyDefinitions = new Map<string, string>();
    const keyframeNames = new Map<string, string>();
    const keyframeContents = new Map<string, string>();
    for (const registered of store.manifests.values()) {
      for (const item of registered.dependencies.properties) {
        propertyDefinitions.set(item.name, item.definition);
      }
      for (const item of registered.dependencies.keyframes) {
        keyframeNames.set(item.name, item.contentKey);
        keyframeContents.set(item.contentKey, item.name);
      }
    }
    for (const item of manifest.dependencies.properties) {
      const existing = propertyDefinitions.get(item.name);
      if (existing !== undefined && existing !== item.definition) {
        warnPrecompileOnce(
          `property-conflict:${item.name}`,
          `[Tasty] Ignoring precompiled styles "${manifest.id}": @property ${item.name} conflicts with an already registered manifest.`,
        );
        return false;
      }
    }
    for (const item of manifest.dependencies.keyframes) {
      const contentForName = keyframeNames.get(item.name);
      const nameForContent = keyframeContents.get(item.contentKey);
      if (
        (contentForName !== undefined && contentForName !== item.contentKey) ||
        (nameForContent !== undefined && nameForContent !== item.name)
      ) {
        warnPrecompileOnce(
          `keyframes-conflict:${item.name}:${item.contentKey}`,
          `[Tasty] Ignoring precompiled styles "${manifest.id}": its keyframe cache metadata conflicts with an already registered manifest.`,
        );
        return false;
      }
    }
  }

  const manifests = (store.manifests ??= new Map());
  const chunks = (store.chunks ??= new Map());
  const dependencies = (store.dependencies ??= new Map());
  manifests.set(manifest.id, manifest);
  dependencies.set(
    manifest.namePrefix,
    mergeDependencies(
      dependencies.get(manifest.namePrefix),
      manifest.dependencies,
    ),
  );
  for (const chunk of manifest.chunks) {
    if (!chunks.has(chunk.lookupKey)) {
      chunks.set(chunk.lookupKey, {
        ...chunk,
        manifestId: manifest.id,
        namePrefix: manifest.namePrefix,
      });
    }
  }
  store.active = true;
  store.revision++;
  return true;
}

export function isPrecompiledManifestRegistered(
  id: string,
  cssHash?: string,
): boolean {
  const manifest = getPrecompileStore().manifests?.get(id);
  return !!manifest && (cssHash === undefined || manifest.cssHash === cssHash);
}
